### ISSUE TITLE
KML Placemarks not located correctly (Geoserver 2.8.x)

### ISSUE THREAD

**Issue by webgismd** [bcgov/databc-web-map-services#1]
## Background

We currently use [GeoServer](http://geoserver.org/), and it's great, except for a little bug. KML Placemarks do not correctly locate when there is a KMSCORE=0 and mode=refresh for SDE EPSG:3005 polygon data. The ground overlay returned is correct, but the KML placemarks don't look like the coordinates have been converted from the native SRS of EPSG:3005. See the bug ticket here posted in the GeoServer community: [https://osgeo-org.atlassian.net/browse/GEOS-7369](https://osgeo-org.atlassian.net/browse/GEOS-7369)

We use GeoServer for our WMS services which outputs KML of spatial data housed in the BC Warehouse. The WMS services are accessible to the public and also consumed by our services, including placemarks the BC Data Catalogue which uses the WMS for map previews of spatial data.
### Story

A a Government of B.C. spatial web developer, I want GeoServer to correctly locate KML placemarks so I can display spatial information accessible to the public via KML/Google Earth.
## Acceptance Criteria
1. KML Placesmarks locate properly when there is a KMSCORE=0 and mode=refresh for SDE EPSG:3005 polygon data.
2. The solutions works within the GeoServer 2.8 code base.
## How to contribute

We will evaluate each pull request and choose the best solution to the issue based on the acceptance criteria. Submit the best solution and you could be paid $1000.

Please read the [Contribution Guidelines](https://github.com/bcgov/databc-web-map-services/blob/master/CONTRIBUTING.md) for the Terms that set the rules for participation in a Pay for Pull, including how you’ll get paid if you are successful.

Have questions? Please post your questions in the comments section below this issue.

If you are interested in working on this issue, please let us know by posting a comment below.

And check out our [Partners page](https://bcdevexchange.org/programs/DataBC%20Web%20Mapping) for more information on our work.

**Comment by myopic73** [comment]
Hi. My name is Michelle Douville if you have any technical questions regarding this issue please let me know!

**Comment by webgismd** [comment]
Hi There! 
My name is Michelle Douville I am the technical contact for this issues. If you have any questions regarding this issue please contact me.

**Comment by lmullane** [comment]
If you are interested in working on this issue, please let us know by posting a comment in this thread.

**Comment by lmullane** [comment]
We received a question about how Pay for Pull works.

The BCDevExchange is experimenting with new procurement methods. Pay for Pull is for small amounts of work where payment is based on how a code solution meets the posted acceptance criteria. 

The opportunity posted on the BCDevExchange is open to anyone to complete.

Unlike more traditional procurement processes there is no upfront contract. Instead we review the submitted work against the Acceptance Criteria and make payment based on its suitability.

One of the things we are trying to work out is how we assign work, as we do not want a duplication of effort. For now, if you are interested in completing this work please post a comment to that effect in this comments section.

Please let us know here if you have more questions.

**Comment by jdeolive** [comment]
Thanks for the clarification on the process. I'm interested in working on this problem. All of the information laid out in the GeoServer ticket is pretty clear, I have enough to start.

**Comment by jdeolive** [comment]
Status update. I've got a local fix for this and have sent a patch over to @myopic73 for acceptance testing. If all goes well I'll start the process of getting the code committed upstream.

**Comment by jdeolive** [comment]
@myopic73 has tested the fix and says it's good to go. The GeoServer pull request has been [submitted](https://github.com/geoserver/geoserver/pull/1609).

**Comment by webgismd** [comment]
Thanks Justin, here is a working example:
http://delivery.openmaps.gov.bc.ca/geo/pub/wms/kml?layers=pub:WHSE_ADMIN_BOUNDARIES.ADM_NR_DISTRICTS_SPG&format_options=kmscore:0;kmattr:true One quick question, are the placemark icons configurable?

**Comment by jdeolive** [comment]
Hey Michelle. As far as I know the only way it's possible to change the icon used for a placemark is if the style on the layer used a point symbolizer that has a graphic on it. Which in this case I don't think would work well because you would be including the icon in both the ground overlay rendering and the generated placemarks added via "kmplacemarks:true".

**Comment by webgismd** [comment]
Hi Justin, Could you make a pull request to this repo (the same as what was done for Geoserver repo).
And include a paypal link and a copy of the terms with your completed information at the end. The Terms are a file in this repo, as an example see here: https://github.com/bcgov/citizen-engagement-web-toolkit/pull/21

**Comment by jdeolive** [comment]
Hi Michelle. Pull request submitted. Let me know if you need any more info for paypal aside from my email address. 

The upstream geoserver pull request has been merged and the change backported to both the 2.9 and 2.8 branches. I'm also attaching the 2.8.1 and 2.8.3 patched jars as you requested. 

[geos-7369-jars.zip](https://github.com/bcgov/databc-web-map-services/files/287963/geos-7369-jars.zip)

**Comment by webgismd** [comment]
Thank you so much Justin! 
I will let @lmullane review the paypal info and get back to you.

**Comment by lmullane** [comment]
Hi @jdeolive, great to hear the patch has been accepted by the GeoServer community. 

The additional PayPal information we need is for you to please update your PR with a PayPal button/email link. 

Could also provide a link to the PR you sent to the GeoServer community as a comment in your PR to this repo?

You will need a PayPal business account to create a PayPal “Pay Now” button/email link at the fixed price of $1000. As per the Terms, developers are responsible for determining, managing and paying any income or other taxes, fees or applicable payments that may be incurred.

Let me know if you have additional questions.

**Comment by jdeolive** [comment]
Thanks for the info @lmullane . PayPal for business is a new thing for me so you'll have to bear with me as I figure out how it works. From what I can tell i need to create an invoice and that will enable the "Pay Now" function. One of the things on the invoice is who to bill. Who should I make out the invoice out to? Thanks!

**Comment by jdeolive** [comment]
The GeoServer pull request that implements this fix is: https://github.com/geoserver/geoserver/pull/1609. It's also been tagged with the commits for the backports to the 2.8.x and 2.9.x GeoServer branches.

**Comment by lmullane** [comment]
Thanks for your questions, @jdeolive. 

Please make out the invoice to the Province of British Columbia and reference this issue's title. If you need a contact, Michelle Douville can be your contact.

Use the Buy Now button option. When you are creating the button it will give you the option of creating code for a website or a link for email. Choose the email link.

Let me know if that works.

**Comment by jdeolive** [comment]
Thanks for the info @lmullane, finally figured out where to set this up. Here is the link you need:

  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=8JJT6U8C2TNPJ

Thanks!

**Comment by lmullane** [comment]
Hi @jdeolive, apologies for being a complete and utter pain. But could you please paste the PayPal link into your Pull Request? We need to do that to comply with the Terms.

**Comment by jdeolive** [comment]
Whoops. My bad sorry, I missed that part. Updating now.

**Comment by lmullane** [comment]
No worries. Best if you paste in the link to the jars into the Pull Request as well. Easier to follow for accounting.

**Comment by jdeolive** [comment]
No problem. Done.

**Comment by lmullane** [comment]
Super! Thank you.

**Comment by webgismd** [comment]
We have accepted a [PR ](https://github.com/bcgov/databc-web-map-services/pull/2) for this issue.
